### ISSUE TITLE
the output of circle GAN

### ISSUE THREAD

**Issue by dyx118186878** [naoto0804/cross-domain-detection#21]
excuse me ， the circle GAN i used only can  output the transformed picture with resolution （256*256），but i noticed that your dt dataset pictures have same resolution as VOC。if possible can you provide the GAN code you used or tell me something about how to modified the GAN net.
 thanks a lot.

**Comment by naoto0804** [comment]
Since the network is fully-convolutional, if you input an image with shape (C, H, W), the shape of the output is also (C, H, W), roughly speaking.

You can specify not to crop during test time, using `--preprocess none` option.
For more details, please refer to the original code
https://github.com/junyanz/pytorch-CycleGAN-and-pix2pix/blob/master/options/base_options.py#L49
